// Generated by CoffeeScript 1.7.1
(function() {
  var $;

  $ = jQuery;

  $.fn.flexibleBox = function(options) {
    var calculateColumnWith;
    this.obj = $(this);
    this.parent = $(this).is("body") ? $(window) : $(this);
    this.settings = $.extend({
      maxColumns: 3,
      breakingWidth: [400, 700, 800],
      minColumnWidth: "300",
      maxWidth: "800",
      gapWidth: "20"
    }, options);
    this.column = this.settings.maxColumns;
    calculateColumnWith = function() {
      var breaking, i, pwidth, width, _i, _len, _ref;
      pwidth = this.parent.width();
      if (pwidth >= this.settings.maxWidth) {
        this.column = this.settings.maxColumns;
        width = (this.settings.maxWidth - this.settings.maxColumns * this.setting.gapWidth) / this.column;
      } else {
        _ref = this.settings.breakingWidth;
        for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
          breaking = _ref[i];
          if (pwidth > this.settings.breakingWidth[i] && pwidth < this.settings.breakingWidth[i + 1] && this.settings.breakingWidth[i + 1]) {
            this.column = i + 1;
          }
        }
        width = pwidth / this.settings.columns;
      }
      return width;
    };
    return this;
  };

}).call(this);
