// Generated by CoffeeScript 1.7.1
(function() {
  describe('Box', function() {
    var box;
    box = new Box({
      "height": 0,
      "width": 2
    });
    it('set option', function() {
      var result;
      box.setOption("height", 1);
      result = box.getOption("height");
      return expect(result).toBe(1);
    });
    return it('get option', function() {
      var result;
      result = box.getOption("width");
      return expect(result).toBe(2);
    });
  });

}).call(this);
