// Generated by CoffeeScript 1.7.1
(function() {
  var Box;

  window.Box = Box = (function() {
    function Box(options) {
      this.options = options;
    }

    Box.prototype.setOption = function(key, value) {
      this.options[key] = value;
      return true;
    };

    Box.prototype.getOption = function(key) {
      return this.options[key];
    };

    return Box;

  })();

}).call(this);
