// Generated by CoffeeScript 1.7.1
(function() {
  var $;

  $ = jQuery;

  $.fn.scrollPresentation = function(options) {
    var obj, settings;
    obj = $(this);
    return settings = $.extend({
      target: $(this)
    }, options);
  };

}).call(this);
