// Generated by CoffeeScript 1.7.1
(function() {
  describe('Box', function() {
    var box, objects;
    box = null;
    objects = [];
    beforeEach(function() {
      return box = new Box({
        "height": 0,
        "top": 2
      });
    });
    it('set option', function() {
      var result;
      box.setOption("height", 1);
      result = box.getOption("height");
      return expect(result).toBe(1);
    });
    it('get option', function() {
      var result;
      result = box.getOption("top");
      return expect(result).toBe(2);
    });
    return it('test objects', function() {
      objects = pushObject(box);
      return expect(objects.length).toBe(1);
    });
  });

}).call(this);
